/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuario;

import logicaNegocio.LogicaLectores;

/**
 *
 * @author dam08
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    
    static LogicaLectores palanthas = new LogicaLectores();
    
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaLectoresAlta = new javax.swing.JFrame();
        panelVentanaLectoresAlta = new javax.swing.JPanel();
        labelLectoresAltaNombre = new javax.swing.JLabel();
        labelLectoresAltaApellidos = new javax.swing.JLabel();
        labelLectoresAltaNif = new javax.swing.JLabel();
        labelLectoresAltaTelefono = new javax.swing.JLabel();
        labelLectoresAltaEmail = new javax.swing.JLabel();
        textFieldLectoresAltaNombre = new javax.swing.JTextField();
        textFieldLectoresAltaApellidos = new javax.swing.JTextField();
        textFieldLectoresAltaNif = new javax.swing.JTextField();
        textFieldLectoresAltaTelefono = new javax.swing.JTextField();
        textFieldLectoresAltaEmail = new javax.swing.JTextField();
        botonLectoresAltaAceptar = new javax.swing.JButton();
        ventanaLectoresVisualizar = new javax.swing.JFrame();
        panelVentanaLectoresVisualizar = new javax.swing.JPanel();
        scrollVentanaLectoresVisualizar = new javax.swing.JScrollPane();
        textAreaLectoresVisualizar = new javax.swing.JTextArea();
        ventanaLectoresBaja = new javax.swing.JFrame();
        panelVentanaLectoresBaja = new javax.swing.JPanel();
        labelLectoresBaja = new javax.swing.JLabel();
        textFieldLectoresBaja = new javax.swing.JTextField();
        botonLectoresBajaAceptar = new javax.swing.JButton();
        ventanaLectoresModificar = new javax.swing.JFrame();
        panelVentanaLectoresModificar = new javax.swing.JPanel();
        labelLectoresModificarNombre = new javax.swing.JLabel();
        labelLectoresModificarApellidos = new javax.swing.JLabel();
        labelLectoresModificarNif = new javax.swing.JLabel();
        labelLectoresModificarTelefono = new javax.swing.JLabel();
        labelLectoresModificarEmail = new javax.swing.JLabel();
        textFieldLectoresModificarNombre = new javax.swing.JTextField();
        textFieldLectoresModificarApellidos = new javax.swing.JTextField();
        textFieldLectoresModificarNif = new javax.swing.JTextField();
        textFieldLectoresModificarTelefono = new javax.swing.JTextField();
        textFieldLectoresAltaEmail1 = new javax.swing.JTextField();
        botonLectoresModificarAceptar = new javax.swing.JButton();
        panelGeneral = new javax.swing.JPanel();
        panelLectores = new javax.swing.JPanel();
        lectoresAlta = new javax.swing.JButton();
        lectoresBaja = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        lectoresBuscar = new javax.swing.JButton();
        lectoresVisualizar = new javax.swing.JButton();
        panelUtilidades = new javax.swing.JPanel();
        utilidadesReset = new javax.swing.JButton();

        panelVentanaLectoresAlta.setBorder(javax.swing.BorderFactory.createTitledBorder("Alta Lector"));

        labelLectoresAltaNombre.setText("Nombre");

        labelLectoresAltaApellidos.setText("Apellidos");

        labelLectoresAltaNif.setText("NIF");

        labelLectoresAltaTelefono.setText("Telefono");

        labelLectoresAltaEmail.setText("Email");

        botonLectoresAltaAceptar.setText("Aceptar");
        botonLectoresAltaAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLectoresAltaAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVentanaLectoresAltaLayout = new javax.swing.GroupLayout(panelVentanaLectoresAlta);
        panelVentanaLectoresAlta.setLayout(panelVentanaLectoresAltaLayout);
        panelVentanaLectoresAltaLayout.setHorizontalGroup(
            panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                .addGroup(panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                                .addComponent(labelLectoresAltaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresAltaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                                .addComponent(labelLectoresAltaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresAltaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                                .addComponent(labelLectoresAltaNif, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresAltaNif, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                                .addComponent(labelLectoresAltaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresAltaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                                .addComponent(labelLectoresAltaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresAltaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(botonLectoresAltaAceptar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelVentanaLectoresAltaLayout.setVerticalGroup(
            panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresAltaNombre)
                    .addComponent(textFieldLectoresAltaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresAltaApellidos)
                    .addComponent(textFieldLectoresAltaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresAltaNif)
                    .addComponent(textFieldLectoresAltaNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresAltaTelefono)
                    .addComponent(textFieldLectoresAltaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresAltaEmail)
                    .addComponent(textFieldLectoresAltaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(botonLectoresAltaAceptar))
        );

        javax.swing.GroupLayout ventanaLectoresAltaLayout = new javax.swing.GroupLayout(ventanaLectoresAlta.getContentPane());
        ventanaLectoresAlta.getContentPane().setLayout(ventanaLectoresAltaLayout);
        ventanaLectoresAltaLayout.setHorizontalGroup(
            ventanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaLectoresAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentanaLectoresAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ventanaLectoresAltaLayout.setVerticalGroup(
            ventanaLectoresAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaLectoresAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentanaLectoresAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelVentanaLectoresVisualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Lectores"));

        textAreaLectoresVisualizar.setColumns(20);
        textAreaLectoresVisualizar.setRows(5);
        scrollVentanaLectoresVisualizar.setViewportView(textAreaLectoresVisualizar);

        javax.swing.GroupLayout panelVentanaLectoresVisualizarLayout = new javax.swing.GroupLayout(panelVentanaLectoresVisualizar);
        panelVentanaLectoresVisualizar.setLayout(panelVentanaLectoresVisualizarLayout);
        panelVentanaLectoresVisualizarLayout.setHorizontalGroup(
            panelVentanaLectoresVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollVentanaLectoresVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVentanaLectoresVisualizarLayout.setVerticalGroup(
            panelVentanaLectoresVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollVentanaLectoresVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ventanaLectoresVisualizarLayout = new javax.swing.GroupLayout(ventanaLectoresVisualizar.getContentPane());
        ventanaLectoresVisualizar.getContentPane().setLayout(ventanaLectoresVisualizarLayout);
        ventanaLectoresVisualizarLayout.setHorizontalGroup(
            ventanaLectoresVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaLectoresVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentanaLectoresVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ventanaLectoresVisualizarLayout.setVerticalGroup(
            ventanaLectoresVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaLectoresVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentanaLectoresVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelVentanaLectoresBaja.setBorder(javax.swing.BorderFactory.createTitledBorder("Baja Lector"));

        labelLectoresBaja.setText("Escribe el ID del lector que deseas dar de baja:");

        botonLectoresBajaAceptar.setText("Aceptar");
        botonLectoresBajaAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLectoresBajaAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVentanaLectoresBajaLayout = new javax.swing.GroupLayout(panelVentanaLectoresBaja);
        panelVentanaLectoresBaja.setLayout(panelVentanaLectoresBajaLayout);
        panelVentanaLectoresBajaLayout.setHorizontalGroup(
            panelVentanaLectoresBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentanaLectoresBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLectoresBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(textFieldLectoresBaja))
                .addContainerGap())
            .addGroup(panelVentanaLectoresBajaLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(botonLectoresBajaAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVentanaLectoresBajaLayout.setVerticalGroup(
            panelVentanaLectoresBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLectoresBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldLectoresBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonLectoresBajaAceptar)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ventanaLectoresBajaLayout = new javax.swing.GroupLayout(ventanaLectoresBaja.getContentPane());
        ventanaLectoresBaja.getContentPane().setLayout(ventanaLectoresBajaLayout);
        ventanaLectoresBajaLayout.setHorizontalGroup(
            ventanaLectoresBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ventanaLectoresBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaLectoresBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVentanaLectoresBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ventanaLectoresBajaLayout.setVerticalGroup(
            ventanaLectoresBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ventanaLectoresBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaLectoresBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVentanaLectoresBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelVentanaLectoresModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar Lector"));

        labelLectoresModificarNombre.setText("Nombre");

        labelLectoresModificarApellidos.setText("Apellidos");

        labelLectoresModificarNif.setText("NIF");

        labelLectoresModificarTelefono.setText("Telefono");

        labelLectoresModificarEmail.setText("Email");

        botonLectoresModificarAceptar.setText("Aceptar");
        botonLectoresModificarAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLectoresModificarAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVentanaLectoresModificarLayout = new javax.swing.GroupLayout(panelVentanaLectoresModificar);
        panelVentanaLectoresModificar.setLayout(panelVentanaLectoresModificarLayout);
        panelVentanaLectoresModificarLayout.setHorizontalGroup(
            panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                .addGroup(panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                                .addComponent(labelLectoresModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                                .addComponent(labelLectoresModificarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresModificarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                                .addComponent(labelLectoresModificarNif, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresModificarNif, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                                .addComponent(labelLectoresModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                                .addComponent(labelLectoresModificarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLectoresAltaEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(botonLectoresModificarAceptar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelVentanaLectoresModificarLayout.setVerticalGroup(
            panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLectoresModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresModificarNombre)
                    .addComponent(textFieldLectoresModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresModificarApellidos)
                    .addComponent(textFieldLectoresModificarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresModificarNif)
                    .addComponent(textFieldLectoresModificarNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresModificarTelefono)
                    .addComponent(textFieldLectoresModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLectoresModificarEmail)
                    .addComponent(textFieldLectoresAltaEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(botonLectoresModificarAceptar))
        );

        javax.swing.GroupLayout ventanaLectoresModificarLayout = new javax.swing.GroupLayout(ventanaLectoresModificar.getContentPane());
        ventanaLectoresModificar.getContentPane().setLayout(ventanaLectoresModificarLayout);
        ventanaLectoresModificarLayout.setHorizontalGroup(
            ventanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ventanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaLectoresModificarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVentanaLectoresModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ventanaLectoresModificarLayout.setVerticalGroup(
            ventanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ventanaLectoresModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaLectoresModificarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVentanaLectoresModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Biblioteca de Palanthas"));

        panelLectores.setBorder(javax.swing.BorderFactory.createTitledBorder("Lectores"));

        lectoresAlta.setText("Alta");
        lectoresAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lectoresAltaMouseClicked(evt);
            }
        });

        lectoresBaja.setText("Baja");
        lectoresBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lectoresBajaMouseClicked(evt);
            }
        });

        Modificar.setText("Modificar");

        lectoresBuscar.setText("Buscar");

        lectoresVisualizar.setText("Visualizar");
        lectoresVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lectoresVisualizarMouseClicked(evt);
            }
        });
        lectoresVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectoresVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLectoresLayout = new javax.swing.GroupLayout(panelLectores);
        panelLectores.setLayout(panelLectoresLayout);
        panelLectoresLayout.setHorizontalGroup(
            panelLectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLectoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lectoresAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lectoresBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lectoresBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lectoresVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLectoresLayout.setVerticalGroup(
            panelLectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLectoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lectoresAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lectoresBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lectoresBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lectoresVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUtilidades.setBorder(javax.swing.BorderFactory.createTitledBorder("Utilidades"));

        utilidadesReset.setText("Reset");
        utilidadesReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadesResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelUtilidadesLayout = new javax.swing.GroupLayout(panelUtilidades);
        panelUtilidades.setLayout(panelUtilidadesLayout);
        panelUtilidadesLayout.setHorizontalGroup(
            panelUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utilidadesReset, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelUtilidadesLayout.setVerticalGroup(
            panelUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utilidadesReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(panelUtilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelUtilidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLectores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lectoresVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectoresVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectoresVisualizarActionPerformed

    private void utilidadesResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadesResetMouseClicked
        // TODO add your handling code here:
        palanthas.reset();
    }//GEN-LAST:event_utilidadesResetMouseClicked

    private void lectoresVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectoresVisualizarMouseClicked
        // TODO add your handling code here:
        ventanaLectoresVisualizar.setVisible(true);
        textAreaLectoresVisualizar.setText(palanthas.visualizarLectores());
    }//GEN-LAST:event_lectoresVisualizarMouseClicked

    private void botonLectoresAltaAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLectoresAltaAceptarMouseClicked
        // TODO add your handling code here:
        palanthas.altaLector(textFieldLectoresAltaNombre.getText(), textFieldLectoresAltaApellidos.getText(), textFieldLectoresAltaNif.getText(), textFieldLectoresAltaTelefono.getText(), textFieldLectoresAltaEmail.getText());
        ventanaLectoresAlta.setVisible(false);
    }//GEN-LAST:event_botonLectoresAltaAceptarMouseClicked

    private void lectoresAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectoresAltaMouseClicked
        // TODO add your handling code here:
        ventanaLectoresAlta.setVisible(true);
    }//GEN-LAST:event_lectoresAltaMouseClicked

    private void botonLectoresBajaAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLectoresBajaAceptarMouseClicked
        // TODO add your handling code here:
        palanthas.bajaLector(Integer.parseInt(textFieldLectoresBaja.getText()));
        ventanaLectoresBaja.setVisible(false);
    }//GEN-LAST:event_botonLectoresBajaAceptarMouseClicked

    private void lectoresBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectoresBajaMouseClicked
        // TODO add your handling code here:
        ventanaLectoresBaja.setVisible(true);
    }//GEN-LAST:event_lectoresBajaMouseClicked

    private void botonLectoresModificarAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLectoresModificarAceptarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLectoresModificarAceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JButton botonLectoresAltaAceptar;
    private javax.swing.JButton botonLectoresBajaAceptar;
    private javax.swing.JButton botonLectoresModificarAceptar;
    private javax.swing.JLabel labelLectoresAltaApellidos;
    private javax.swing.JLabel labelLectoresAltaEmail;
    private javax.swing.JLabel labelLectoresAltaNif;
    private javax.swing.JLabel labelLectoresAltaNombre;
    private javax.swing.JLabel labelLectoresAltaTelefono;
    private javax.swing.JLabel labelLectoresBaja;
    private javax.swing.JLabel labelLectoresModificarApellidos;
    private javax.swing.JLabel labelLectoresModificarEmail;
    private javax.swing.JLabel labelLectoresModificarNif;
    private javax.swing.JLabel labelLectoresModificarNombre;
    private javax.swing.JLabel labelLectoresModificarTelefono;
    private javax.swing.JButton lectoresAlta;
    private javax.swing.JButton lectoresBaja;
    private javax.swing.JButton lectoresBuscar;
    private javax.swing.JButton lectoresVisualizar;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelLectores;
    private javax.swing.JPanel panelUtilidades;
    private javax.swing.JPanel panelVentanaLectoresAlta;
    private javax.swing.JPanel panelVentanaLectoresBaja;
    private javax.swing.JPanel panelVentanaLectoresModificar;
    private javax.swing.JPanel panelVentanaLectoresVisualizar;
    private javax.swing.JScrollPane scrollVentanaLectoresVisualizar;
    private javax.swing.JTextArea textAreaLectoresVisualizar;
    private javax.swing.JTextField textFieldLectoresAltaApellidos;
    private javax.swing.JTextField textFieldLectoresAltaEmail;
    private javax.swing.JTextField textFieldLectoresAltaEmail1;
    private javax.swing.JTextField textFieldLectoresAltaNif;
    private javax.swing.JTextField textFieldLectoresAltaNombre;
    private javax.swing.JTextField textFieldLectoresAltaTelefono;
    private javax.swing.JTextField textFieldLectoresBaja;
    private javax.swing.JTextField textFieldLectoresModificarApellidos;
    private javax.swing.JTextField textFieldLectoresModificarNif;
    private javax.swing.JTextField textFieldLectoresModificarNombre;
    private javax.swing.JTextField textFieldLectoresModificarTelefono;
    private javax.swing.JButton utilidadesReset;
    private javax.swing.JFrame ventanaLectoresAlta;
    private javax.swing.JFrame ventanaLectoresBaja;
    private javax.swing.JFrame ventanaLectoresModificar;
    private javax.swing.JFrame ventanaLectoresVisualizar;
    // End of variables declaration//GEN-END:variables
}
